### ISSUE TITLE
Hve Notes 小白上手教程 | Hve Notes

### ISSUE THREAD

**Issue by EryouHao** [EryouHao/EryouHao.github.io#11]
https://fehey.com/post/hve-notes-start/

**Comment by babyshit** [comment]
可以说是非常棒了！虽然客户端功能还不是很完善，但是已经让我一个小白用到了静态博客~
非常感谢！

**Comment by EryouHao** [comment]
> @babyshit
> 可以说是非常棒了！虽然客户端功能还不是很完善，但是已经让我一个小白用到了静态博客~
> 非常感谢！

感谢支持，会越来越完善的，欢迎关注！

**Comment by Adiwon** [comment]
之前折腾hexo搞得头都大了，配置文件基本上一个作者一套写法，心累无比，有这样的工具真是太好了。

**Comment by EryouHao** [comment]
> @Adiwon
> 之前折腾hexo搞得头都大了，配置文件基本上一个作者一套写法，心累无比，有这样的工具真是太好了。

感谢支持，欢迎关注，后面会增加更多功能和更稳定的。

**Comment by bestop** [comment]
非常棒的工具！
有个问题，如果我在github上已经有一个静态博客，使用这个工具同步后，是否会把原来的主题覆盖？

**Comment by EryouHao** [comment]
> @bestop
> 非常棒的工具！
> 有个问题，如果我在github上已经有一个静态博客，使用这个工具同步后，是否会把原来的主题覆盖？

会，这个工具会把构建后的静态文件推送到对应的仓库

**Comment by yukinryou** [comment]
哈哈，测试

**Comment by lupus721** [comment]
**看样子是个不错的选择，持续观望一段时间先**

**Comment by ghost** [comment]
请问下作者，现在点击同步按钮后，一直在转圈。是因为我配置有误吗？

**Comment by ghost** [comment]
补充一下，我只是装了git和hve notes，git还需要再terminal里配置吗？不需要了吧？是不是这里的问题

**Comment by jacklyli** [comment]
> @loftyworm

git config user.name"用户名" 否则无法同步。

**Comment by EryouHao** [comment]
> @loftyworm
> 补充一下，我只是装了git和hve notes，git还需要再terminal里配置吗？不需要了吧？是不是这里的问题

不需要配置，一般情况下是配置错了或者是分支不是 master（当前版本没有适配其他分支，下版本修复） 导致的，若还有问题可以加群以获得更即时的回复，感谢支持

**Comment by ghost** [comment]
> @jacklyli
> > @loftyworm
> 
> git config user.name"用户名" 否则无法同步。

尝试了，但是依然没能解决。。。。依然感谢。

**Comment by jojojonan** [comment]
0.7.6 版用坚果云同步到另一台电脑，在另一台电脑上把源文件指向云同步文件，检测远程连接，提示“远程连接失败，请检查仓库、用户名和 Token 设置”，找不到原因。

**Comment by EryouHao** [comment]
> @jojojonan
> 0.7.6 版用坚果云同步到另一台电脑，在另一台电脑上把源文件指向云同步文件，检测远程连接，提示“远程连接失败，请检查仓库、用户名和 Token 设置”，找不到原因。

你的另一台设备是否安装了 Git，另外在应用中是否可以看到同步过来的配置信息（域名、token、仓库等等）

**Comment by jojojonan** [comment]
> @EryouHao
> > @jojojonan
> > 0.7.6 版用坚果云同步到另一台电脑，在另一台电脑上把源文件指向云同步文件，检测远程连接，提示“远程连接失败，请检查仓库、用户名和 Token 设置”，找不到原因。
> 
> 你的另一台设备是否安装了 Git，另外在应用中是否可以看到同步过来的配置信息（域名、token、仓库等等）

安装了git，在应用中也看到了配置信息。提示“无法远程连接”后我又重装了hve，还是远程连接失败……

**Comment by linancc** [comment]
创意非常好，博客爱好者可以专注写作本身，不用管理 hexo 复杂的配置，期待更多个性主题

**Comment by pcysanji** [comment]
希望有更多主题  很棒 ，简单好多

**Comment by EryouHao** [comment]
> @pcysanji
> 希望有更多主题  很棒 ，简单好多

感谢支持🙏

**Comment by EryouHao** [comment]
> @linancc
> 创意非常好，博客爱好者可以专注写作本身，不用管理 hexo 复杂的配置，期待更多个性主题

感谢支持，敬请关注🙏

**Comment by snowXT** [comment]
一样的配置 一直提示 远程链接失败

**Comment by EryouHao** [comment]
> @luhuiming
> 一样的配置 一直提示 远程链接失败

配置没问题的话，可能是 git 环境变量问题，若还是未解决，可加群解决下，感谢支持

**Comment by edwardzjl** [comment]
请问一下有没有远程仓库同步到本地的功能。
比如我在我的笔记本上安装了hve notes，写了两篇文章，同步到了github.io
然后我在我的台式机上又安装了一遍，但是这时候如果我在台式机上同步，之前写好的文章就没了

**Comment by EryouHao** [comment]
> @edwardzjl
> 请问一下有没有远程仓库同步到本地的功能。
> 比如我在我的笔记本上安装了hve notes，写了两篇文章，同步到了github.io
> 然后我在我的台式机上又安装了一遍，但是这时候如果我在台式机上同步，之前写好的文章就没了
> 

目前没有，您可以通过将源文件夹设置到同步工具（OneDrive、百度网盘、iCloud、Dropbox 等）所在的文件夹，进行多设备同步

**Comment by cunyu1943** [comment]
博主，请问我填入信息之后为什么还是检测链接不上呢

**Comment by boycema** [comment]
按照上面配置了之后还是提示：必须完成配置才能同步哦！

**Comment by EryouHao** [comment]
> @mataoqun
> 按照上面配置了之后还是提示：必须完成配置才能同步哦！

初次使用的时候点击检测远程链接成功后，需要再点击下保存就可以了

**Comment by littlecorgi-twk** [comment]
谢谢博主，配置成功了

**Comment by pcysanji** [comment]
老大，怎么添加友链啊？  目前没有这个功能吧

**Comment by wudening** [comment]
客户端可以添加一个搜索文章的功能，支持同时按照自己写的文章标题和文章关键字的查找

**Comment by wudening** [comment]
弄个账户登录，然后做了云同步功能，VIP收费

**Comment by wudening** [comment]
使用起来是简单些，目前存在的问题是，这个客户端就是个本地编辑器，没有数据同步的功能，还有就是图片无法确定显示的大小

**Comment by zhangxin23333** [comment]
不好意思 纯小白 配置好之后 打开为什么地址还是本地？

**Comment by edwardzjl** [comment]
你好，我遇到个问题，就是我发现我的文章需要通过https访问，但是我在博客里点击文章标题默认是通过http打开，无法访问文章页面。如果手动改成https就可以访问了。请问是什么问题？

**Comment by YangSX21** [comment]
你好，我如果更换电脑该如何进行同步。是只要把源文件夹的内容复制过去就可以了吗？

**Comment by EryouHao** [comment]
> @YangSX21
> 你好，我如果更换电脑该如何进行同步。是只要把源文件夹的内容复制过去就可以了吗？

是的，如果是永久电脑更换可复制过去，如果想日常使用多台电脑同步管理博客，可参考：https://gridea.dev/docs/faq.html

**Comment by EryouHao** [comment]
> @edwardzjl
> 你好，我遇到个问题，就是我发现我的文章需要通过https访问，但是我在博客里点击文章标题默认是通过http打开，无法访问文章页面。如果手动改成https就可以访问了。请问是什么问题？

设置域名的时候写成 https 的

**Comment by edwardzjl** [comment]
> > @edwardzjl
> > 你好，我遇到个问题，就是我发现我的文章需要通过https访问，但是我在博客里点击文章标题默认是通过http打开，无法访问文章页面。如果手动改成https就可以访问了。请问是什么问题？
> 
> 设置域名的时候写成 https 的

设置里的域名是https的，博客主页也是https的，但是点击到具体的某一篇文章里去就是http的了。

**Comment by EryouHao** [comment]
@edwardzjl 我访问了一下你的博客是可以正常访问文章的，若还是有此问题，可以安装最新版试试

**Comment by jasonzhouu** [comment]
这让部署静态博客更加**简单方便**了

**Comment by theck17** [comment]
大佬您好，我测试远程连接的时候的报错message: "fatal: No such remote 'origin'，这是因为必须要建立一个公共仓库么，私人仓库可以么

**Comment by houziershi** [comment]
6666

**Comment by qq1332783374** [comment]
大神您好，我想请问一下，能不能把仓库换成自己的云服务器

**Comment by EryouHao** [comment]
> @qq1332783374
> 大神您好，我想请问一下，能不能把仓库换成自己的云服务器

可以的，暂时可以手动将构建后的静态文件 `output` 文件夹，上传到自己的服务器去

**Comment by qq1332783374** [comment]
懂了，谢谢大神指点。




------------------ 原始邮件 ------------------
发件人: "fehey"<notifications@github.com>;
发送时间: 2019年4月25日(星期四) 中午11:37
收件人: "EryouHao/EryouHao.github.io"<EryouHao.github.io@noreply.github.com>;
抄送: "Limited edition@💝Ni"<1332783374@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [EryouHao/EryouHao.github.io] Hve Notes 小白上手教程 | Hve Notes (#11)



 
@qq1332783374
 大神您好，我想请问一下，能不能把仓库换成自己的云服务器
  
可以的，暂时可以手动将构建后的静态文件 output 文件夹，上传到自己的服务器去

**Comment by caribow** [comment]
为啥我的博客地址在浏览器输入后打不开呢

**Comment by edwardzjl** [comment]
> @EryouHao
> @edwardzjl 我访问了一下你的博客是可以正常访问文章的，若还是有此问题，可以安装最新版试试

在自己的 repository 启用了强制 https，然后清除了一下 chrome 缓存，现在好了，谢谢！

**Comment by Hymnsin** [comment]
感谢🙏

**Comment by Hymnsin** [comment]
感谢🙏

**Comment by qq1332783374** [comment]
大神您好，在这里我想给您提出一些建议。在编辑文章的时候，想添加图片就要重新移到最顶部然后再添加。虽然说Markdown 可以直接写路径什么的，但还是显得有点麻烦。所以就想请问，下一次更新考虑把文章编写的功能导航做成吸顶的效果，说不定会用户体验会更好。谢谢，望采纳。

**Comment by aoaim** [comment]
谢谢作者给我们带来的Gridea！希望作者能坚持下去，我们一起让Gridea发展壮大！

**Comment by 662077** [comment]
非常感谢，希望不久以后能出像hexo那样的很好看的主题

**Comment by 662077** [comment]
> @wkh19960317
> 大佬您好，我测试远程连接的时候的报错message: "fatal: No such remote 'origin'，这是因为必须要建立一个公共仓库么，私人仓库可以么


不能用私人仓库，域名无法加载，之前我是用hexo卡住就是应为搭建了私人仓库的坑

**Comment by ghost** [comment]
作者有比特币地址没？小小的支持下你。这是我一直希望的工具，虽然还不完整，但已经大大的超过预期了。之前差点被hexo搞疯，写个博客搞得跟部署web项目一样。

**Comment by EryouHao** [comment]
> 作者有比特币地址没？小小的支持下你。这是我一直希望的工具，虽然还不完整，但已经大大的超过预期了。之前差点被hexo搞疯，写个博客搞得跟部署web项目一样。

@initsysctrl 感谢老板的游艇😂 1CRSMrfWUX8WKivzLmTPbgp4YXUw2yCKb8

**Comment by lucid-dream** [comment]
发表文章，如何切换markdown源码编写模式？

**Comment by EryouHao** [comment]
> 发表文章，如何切换markdown源码编写模式？

@lucid-dream 目前的编写模式就是 markdown 的编写模式。文章内支持 HTML 代码

**Comment by gz222** [comment]
远程连接失败，请检查仓库、用户名和 Token 设置
应该没什么问题啊，虽然第一次用，git安装后需要单独配置吗

**Comment by mrsensen** [comment]
你好，之前用GitHub Pages+Hugo搭建的博客，能直接使用该工具当做客户端吗

**Comment by GuoRan18** [comment]
主题可以再多点

**Comment by handloong** [comment]
gittalk 提示 Error: Not Found.
请问是为啥呢。。点击github登录会返回首页。

**Comment by EryouHao** [comment]
> @handloong
> gittalk 提示 Error: Not Found.
> 请问是为啥呢。。点击github登录会返回首页。

这是因为 Github OAuth Application 中的 Homepage URL 和 Authoration callback URL 有误。若是有自定义域名需填写自定义域名

**Comment by EryouHao** [comment]
> @mrsensen
> 你好，之前用GitHub Pages+Hugo搭建的博客，能直接使用该工具当做客户端吗

可以将原来的 Markdown 文件导入试试

**Comment by ljh2023** [comment]
666666

**Comment by Jeffrey28** [comment]
就是gitalk无法生效呢

**Comment by LIXU103934** [comment]
博主 您好 ：我配置的这个 没有CSS样式

**Comment by wmltyq** [comment]
我用Coding Pages搭建，但是Gitalk显示Error: Not Found.

**Comment by ghost** [comment]
您好：我没太能明白您的意思，您可以简述详细一些吗？

王明 <notifications@github.com> 于2019年5月20日周一 下午12:00写道：

**Comment by Monologuethl** [comment]
配置好后，打开出现
404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

**Comment by ghost** [comment]
请问下载安装好Git后，然后同步出现错误，一般有什么类型的错误？小白，不是很懂，想弄个博客以后谢谢文章！谢谢

**Comment by yizhiGao2018** [comment]
配置不好啊，点击检测远程连接提示远程连接失败，但是都是按照提示说的方法做的

**Comment by yizhiGao2018** [comment]
完全按照配置写的但远程连接一直失败……
求大神告知错误

**Comment by zhyfans** [comment]
都搭建好了，就是有一个问题，每次同步完，必须清理浏览器缓存，才能看到博客页面的文章有更新，这个有办法解决吗

**Comment by hello432369** [comment]
> @zhyfans
> 都搭建好了，就是有一个问题，每次同步完，必须清理浏览器缓存，才能看到博客页面的文章有更新，这个有办法解决吗

静态页面就是这样的，不然叫动态了。

**Comment by hello432369** [comment]
> @yizhiGao2018
> 完全按照配置写的但远程连接一直失败……
> 求大神告知错误

git安装完后重启电脑，我是这么解决了

**Comment by hello432369** [comment]
能不能做个gitalk设置教程视频？按照这个弄完之后提示：未找到相关的 Issues 进行评论

**Comment by mrsensen** [comment]
> 能不能做个gitalk设置教程视频？按照这个弄完之后提示：未找到相关的 Issues 进行评论

本地预览的话，这个是正常现象，部署到GitHub pages就可以了

**Comment by coderbean** [comment]
非常清新的一个静态博客

**Comment by EvisonLee** [comment]
在配置时始终显示远程连接失败，报错提示如下{message: "Error: spawn git ENOENT↵    at Process.ChildProces…ickCallback (internal/process/next_tick.js:63:19)", success: false}，麻烦大佬指点一下

**Comment by left001** [comment]
小白求指导：
新建了库之后链接打卡404，请问是什么原因呢。
我看了其他人的页面发现存储库确实不一样，但不知道什么原因。。

**Comment by left001** [comment]
我的问题自己已经解决了哈！

**Comment by 253752742** [comment]
我这边检测远程链接是成的，保存了，但是同步的时候出错了，该如何解决？

**Comment by EryouHao** [comment]
> 在配置时始终显示远程连接失败，报错提示如下{message: "Error: spawn git ENOENT↵ at Process.ChildProces…ickCallback (internal/process/next_tick.js:63:19)", success: false}，麻烦大佬指点一下

@EvisonLee 请看 FAQ https://gridea.dev/docs/faq.html

**Comment by 253752742** [comment]
可以回答一下吗？我这边配置都成功，检测远程链接也成功，保存也成功，但是为什么同步的时候出错？

**Comment by EryouHao** [comment]
> 可以回答一下吗？我这边配置都成功，检测远程链接也成功，保存也成功，但是为什么同步的时候出错？

@253752742 我看你的仓库把Gridea 的文件夹里的内容都上传上去了，不太清楚这个是怎么操作的，理论上只会上传 output 文件夹内容，建议把 Gridea 文件夹删除，然后重新启动应用初始化，或者在应用中点击：系统 -> 源文件夹，重新选择一个空的源文件夹目录

**Comment by 253752742** [comment]
> @EryouHao
> > 可以回答一下吗？我这边配置都成功，检测远程链接也成功，保存也成功，但是为什么同步的时候出错？
> 
> @253752742 我看你的仓库把Gridea 的文件夹里的内容都上传上去了，不太清楚这个是怎么操作的，理论上只会上传 output 文件夹内容，建议把 Gridea 文件夹删除，然后重新启动应用初始化，或者在应用中点击：系统 -> 源文件夹，重新选择一个空的源文件夹目录

因为不清楚文件是怎么部署的，所以整个文件内容都上传了，我重新尝试一下，在本地文件夹中，git init 是在output文件夹下运行这个命令吗？还有我不太清楚，系统->源文件夹，是选择一个空的文件即可吗？

**Comment by EryouHao** [comment]
> > @EryouHao
> > > 可以回答一下吗？我这边配置都成功，检测远程链接也成功，保存也成功，但是为什么同步的时候出错？
> > 
> > 
> > @253752742 我看你的仓库把Gridea 的文件夹里的内容都上传上去了，不太清楚这个是怎么操作的，理论上只会上传 output 文件夹内容，建议把 Gridea 文件夹删除，然后重新启动应用初始化，或者在应用中点击：系统 -> 源文件夹，重新选择一个空的源文件夹目录
> 
> 因为不清楚文件是怎么部署的，所以整个文件内容都上传了，我重新尝试一下，在本地文件夹中，git init 是在output文件夹下运行这个命令吗？还有我不太清楚，系统->源文件夹，是选择一个空的文件即可吗？

一切运行都是自动的，不需要手动执行任何命令， `系统->源文件夹`，指的是博客文件的源文件夹，默认启动应用时，会在你的 `文档` 文件夹内生成一个名称为 `Gridea` 的文件夹，当然你也可以修改为其他的文件夹，用来做多博客管理或者多设备同步等使用

**Comment by 253752742** [comment]
> @EryouHao
> > > @EryouHao
> > > > 可以回答一下吗？我这边配置都成功，检测远程链接也成功，保存也成功，但是为什么同步的时候出错？
> > > 
> > > 
> > > @253752742 我看你的仓库把Gridea 的文件夹里的内容都上传上去了，不太清楚这个是怎么操作的，理论上只会上传 output 文件夹内容，建议把 Gridea 文件夹删除，然后重新启动应用初始化，或者在应用中点击：系统 -> 源文件夹，重新选择一个空的源文件夹目录
> > 
> > 因为不清楚文件是怎么部署的，所以整个文件内容都上传了，我重新尝试一下，在本地文件夹中，git init 是在output文件夹下运行这个命令吗？还有我不太清楚，系统->源文件夹，是选择一个空的文件即可吗？
> 
> 一切运行都是自动的，不需要手动执行任何命令， `系统->源文件夹`，指的是博客文件的源文件夹，默认启动应用时，会在你的 `文档` 文件夹内生成一个名称为 `Gridea` 的文件夹，当然你也可以修改为其他的文件夹，用来做多博客管理或者多设备同步等使用

我现在修改了git上的文件，检测远程链接成功，保存后，为什么同步还是不行？不知道该怎么配置了，麻烦告之一声，谢谢

**Comment by sevenwoood** [comment]
可能是因为我笨，跟着做完后打开页面竟然是404……

**Comment by GooZy** [comment]
使用`yarn electron:serve` 命令，各种需要vue的依赖，希望文档能写清楚都需要什么依赖

**Comment by lucid-dream** [comment]
??

**Comment by GooZy** [comment]
哈哈哈，之前智障了，没下载客户端，直接按照readme去配置开发环境了，搞得自己怀疑人生。

lucid-dream <notifications@github.com> 于2019年6月2日周日 上午10:35写道：

**Comment by zhangjinmiao** [comment]
Coding Pages 配置不成功，给个例子吧

**Comment by AWhiteMouse** [comment]
仓库名、用户名、token我都检查过了，但是总是提示检查

**Comment by AWhiteMouse** [comment]
No such remote 'origin'
难道是因为我的仓库用户名和github用户名不一致的原因？

**Comment by tanabalu** [comment]
开始一直在报fatal: No such remote 'origin'错误，检查过用户名、邮箱和Token都没错，重启大法也没用。然后联想到我在安装客户端的时候修改了安装的位置，于是在客户端的系统选项中修改了源文件夹的位置指向我安装的位置，就没有报错了。

**Comment by xingshengji** [comment]
非常感谢您提供的解决方案，让我等可以专心创作！

**Comment by 1551146844** [comment]
你好，现在有个问题是这样的，远程仓库都已建设好，我本地没有安装git,也没有本地的SSH配置到github,是不能远程链接成功的吗？

**Comment by EryouHao** [comment]
> @1551146844
> 你好，现在有个问题是这样的，远程仓库都已建设好，我本地没有安装git,也没有本地的SSH配置到github,是不能远程链接成功的吗？

是的。必须安装 git，同时利用 token 才可以同步到 Github 哦

**Comment by 1551146844** [comment]
> @EryouHao
> > @1551146844
> > 你好，现在有个问题是这样的，远程仓库都已建设好，我本地没有安装git,也没有本地的SSH配置到github,是不能远程链接成功的吗？
> 
> 是的。必须安装 git，同时利用 token 才可以同步到 Github 哦

如果我在一个电脑上配置了github,在另外一台电脑上安装了git和软件，是不能进行同步的吗？

**Comment by heihei12305** [comment]
未找到相关的 Issues 进行评论

请联系 @***** 初始化创建 这个怎么弄呢

**Comment by heihei12305** [comment]
知道啦，蟹蟹！很不错哦

**Comment by Hulenkius** [comment]
看到知乎说：“**……Gridea这个人性化的软件**”来的。
 
真方便哪……一反我对博客只能像Hexo一样繁琐的印象^

**Comment by AM0205** [comment]
客户端配置一直提示远程连接失败呢

**Comment by tanabalu** [comment]
如果在安装的时候你修改了安装位置，那么在客户端的系统菜单栏中要修改源文件夹位置


 
---原始邮件---
发件人: "AM0205"<notifications@github.com>
发送时间: 2019年6月15日(星期六) 下午5:18
收件人: "EryouHao/EryouHao.github.io"<EryouHao.github.io@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"chenxin"<1586671591@qq.com>;
主题: Re: [EryouHao/EryouHao.github.io] Hve Notes 小白上手教程 | Hve Notes (#11)



客户端配置一直提示远程连接失败呢

**Comment by DarcySHN** [comment]
纯小白请教一下，把域名设置成 Github Pages 模式，但是访问就跳 404 是怎么回事呢？

**Comment by geosmart** [comment]
超级赞的产品化

**Comment by ahaow** [comment]
很棒，配置简单方便，非常感谢

**Comment by gmyanfeng** [comment]
你好，我点击同步的时候提示：『抱歉，同步遇到了错误，请联系作者』

**Comment by Liaoyaqin520** [comment]
- 感谢老板提供这么优秀的工具！

**Comment by yangxiaoge** [comment]
很棒的博客！

**Comment by WhyNotZRN** [comment]
很棒的博客！

**Comment by Eternal0527** [comment]
感谢你的帮助，我成功用上了GitHub白嫖来的博客。只是客户端支持的功能真的是不算完善，你的博客写的好有感觉啊！！！

**Comment by EVINK** [comment]
coding 上应该咋用啊， "Test Remote Error:  fatal: 不是一个 git 仓库（或者任何父目录）：.git "

**Comment by kongzhongfeima** [comment]
> @left001
> 我的问题自己已经解决了哈！
同学  小白想问你的404怎么解决的呀  
谢谢

**Comment by kongzhongfeima** [comment]
没事了   已解决：）

**Comment by lizhucao** [comment]
评论怎么初始化呀

**Comment by pointerZhang** [comment]
非常的ncie

**Comment by Marco233** [comment]
不好意思，想问下，配置完检查远程连接都通了，git仓库了有临时的模板文件，为啥访问的时候提示还是404

**Comment by EryouHao** [comment]
@Marco233 将仓库名改为 `marco233.github.io`

**Comment by Marco233** [comment]
> @kongzhongfeima
> 
> > @left001
> > 我的问题自己已经解决了哈！
> 同学  小白想问你的404怎么解决的呀  
> 谢谢
> 
> 

想问下咋解决的？

**Comment by Marco233** [comment]
> @EryouHao
> @Marco233 将仓库名改为 `marco233.github.io`

这样吗？那感觉我要重新换个账号了，这个账号不太好

**Comment by luobin5** [comment]
很开心，作为一个小白，用Gridea很轻易就成功弄好了，写文章也很方便，非常感谢。请问可以教我把那个内置fly主题的字体改为普通的黑色字体吗

**Comment by zfwsy** [comment]
太感谢了！

**Comment by sukai-cheng** [comment]
心累啊，两个小时了，页面一直是404的状态，炸雷了我

**Comment by sukai-cheng** [comment]
同步非常慢

**Comment by sukai-cheng** [comment]
> @left001
> 我的问题自己已经解决了哈！

请问你是怎么解决的？我目前遇到这个问题

**Comment by cherryzhangqianqian** [comment]
以前用hexo建立过一个站点的博客 新开一个仓库不会覆盖掉么 小白

**Comment by EryouHao** [comment]
@cherryzhangqianqian 如果是用同一个仓库的话，会覆盖掉的

**Comment by tantainyuan** [comment]
我之前就用过这个，现在想继续写，同步失败额，有办法解决么，还是说得把仓库的东西删掉才能同步

**Comment by cherryzhangqianqian** [comment]
我是直接😂😂😂重新搞了 不过应该可以把 文章拷贝过来吧




| |
m18552370206
|
|
邮箱：18552370206@163.com
|

Signature is customized by Netease Mail Master

在2019年11月13日 10:05，tantainyuan 写道：

我之前就用过这个，现在想继续写，同步失败额，有办法解决么，还是说得把仓库的东西删掉才能同步

**Comment by hsxyhao** [comment]
看到很多人遇到远程连接失败以及同步失败的问题，我配置的时候也出现过，看了下后台提示的信息，有一条信息是 “Test Remote Error:  fatal: 不是一个 git 仓库（或者任何父目录）：.git”，大致的意思就是Gridea的输出目录不是一个git仓库，我这边解决的方案是将Gridea/output(在Gridea系统配置的源文件夹可以找到)的输出目录初始化为一个git仓库，然后将github上的远程地址使用git remote命令添加上，操作完之后远程连接以及同步都没有问题了，希望能帮到大家:)

**Comment by cherryzhangqianqian** [comment]
不是说吧gridea的目录直接拷贝过去就好了么




| |
m18552370206
|
|
邮箱：18552370206@163.com
|

Signature is customized by Netease Mail Master

在2019年11月13日 11:41，hsxyhao 写道：

看到很多人遇到远程连接失败以及同步失败的问题，我配置的时候也出现过，看了下后台提示的信息，有一条信息是 “Test Remote Error: fatal: 不是一个 git 仓库（或者任何父目录）：.git”，大致的意思就是Gridea的输出目录不是一个git仓库，我这边解决的方案是将output的输出目录初始化为一个git仓库，然后将github上的远程地址使用git remote命令添加上，操作完之后远程连接以及同步都没有问题了，希望能帮到大家:)

**Comment by hsxyhao** [comment]
> @cherryzhangqianqian
> 不是说吧gridea的目录直接拷贝过去就好了么
> 
> 
> 
> 
> | |
> m18552370206
> |
> |
> 邮箱：18552370206@163.com
> |
> 
> Signature is customized by Netease Mail Master
> 
> 在2019年11月13日 11:41，hsxyhao 写道：
> 
> 看到很多人遇到远程连接失败以及同步失败的问题，我配置的时候也出现过，看了下后台提示的信息，有一条信息是 “Test Remote Error: fatal: 不是一个 git 仓库（或者任何父目录）：.git”，大致的意思就是Gridea的输出目录不是一个git仓库，我这边解决的方案是将output的输出目录初始化为一个git仓库，然后将github上的远程地址使用git remote命令添加上，操作完之后远程连接以及同步都没有问题了，希望能帮到大家:)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

我是新建的，迁移没有弄过，可能有点区别，感觉只要git地址对了，应该就没有问题

**Comment by anxinweb** [comment]
gridea这是一个非常好的项目，使原本复杂化的东西简化，使写博客的人更加专注写博客，小白很容易上手。很支持这个项目的持续发展。

**Comment by phpll** [comment]
我按照那你的弄怎么   远程连接失败，请检查仓库、用户名和 Token 设置

**Comment by QQFloatingice** [comment]
话说评论经常鬼畜是什么问题

**Comment by jiuqianqi10000** [comment]
gitalk Error: Network Error咋搞啊

**Comment by luobin5** [comment]
> gitalk Error: Network Error咋搞啊

我也遇到过这种情况，主要和网络有关，当网络不能正常访问Github的时候就会这样，好像换一下网络或者改下dns就行了，具体我也不知道是什么原因。

**Comment by hjxhjx2007** [comment]
为什么我的远程连接测试过，没问题，但是同步之后没反应啊QAQ（github已经给我发邮件了）

**Comment by wujinpai** [comment]
Linux下centos没玩过这内安装包，没有可视化面板如何操作客户端？

**Comment by sy132** [comment]
作者能写一下如何通过SFTP搭建站点嘛，最近阿里云有高校计划有点想自己租个服务器买个域名弄一下，麻烦大大了！

**Comment by qq923340082** [comment]
麻烦请教下，网站那个库啊什么的弄好后，同步完成后，可以预览，但是复制连接在引擎里却搜不到，结果404.这是什么原因

**Comment by LiuXuejun123** [comment]
评论 note found  主题walker

**Comment by HarryCuiCAS** [comment]
博主请问，怎么把写好的文章添加到自定义的菜单里啊

**Comment by ghost** [comment]
大佬，请问一下自带的 Note 主题没有`fancybox`功能吗?
